### ISSUE TITLE
Use the proper name for Jesus' foreskin

### ISSUE THREAD

**Issue by 1nickt** [tobyink/p5-acme-conspiracytheory-random#1]
`s/Jesus's foreskin/the Holy Prepuce/` ?

[wikipedia](https://en.wikipedia.org/wiki/Holy_Prepuce)

**Comment by tobyink** [comment]
I'd probably want to keep "Jesus's foreskin" but would accept a patch which added "the Holy Prepuce" in addition. At one time, the Catholic Church is thought to have acknowledged at least eighteen foreskins as belonging to Jesus, so I don't think it would be a stretch for this module to have two.

**Comment by 1nickt** [comment]
Submitted, thanks. (It's just such a great word!)
