### ISSUE TITLE
Electrons DO have mass

### ISSUE THREAD

**Issue by benkasminbullock** [tobyink/p5-acme-conspiracytheory-random#3]
https://github.com/tobyink/p5-acme-conspiracytheory-random/blob/master/lib/Acme/ConspiracyTheory/Random.pm#L1447

But they DO have mass:

https://www.britannica.com/science/electron

The rest mass of the electron is 9.1093837015 × 10−31 kg

**Comment by tobyink** [comment]
As somebody who has put on weight over lockdown, I wish it were a matter of a mere 9.1093837015 × 10−31 kg.

Yeah, I'm aware electrons have some mass, though it's fairly negligible.What I really meant was mass comparable to protons and neutrons, but I phrased it very badly. I'll come up with better wording.
